### PR TITLE
Contributte style

### PR DESCRIPTION
**Pull request by petrparolek**
- added editorconfig
- added git attributes
- added licence file
- added GitHub Actions
- added kodiak
- ninjify CS
- ReadMe++

### CODE REVIEW

**Comment by petrparolek** [comment]
@TonnyJe Could you look at failing tests please? I don't know mockery more.

@f3l1x I polished this package

**Comment by f3l1x** [comment]
Cool! :-)

**Comment by f3l1x** [comment]
I will merge it, do you agree @TonnyJe?

**Comment by TonnyJe** [comment]
Yea

**Pull request merged**
